services:
  app:
    image: mysociety/test_repo:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/test_repo      
    volumes:
      - ./:/workspaces/test_repo/